Add base shortcuts
music-assistant/frontend pull request #517
Opened 2024-05-30 19:35 UTC by max246

This is part of the request #1645   , it adds shortcuts to the UI

CTRL + ALT + S Enable/Disable shuffle
CTRL + ALT + R Enable/Disable repeat
CTRL + ALT + 1 Go home
CTRL + ALT + 2 Go search
CTRL + ALT + 3 Go Artists
CTRL + ALT + 4 Go Albums
CTRL + ALT + 4 Go Albums
CTRL + ALT + 5 Go Tracks
CTRL + ALT + 6 Go Playlists
CTRL + ALT + 7 Go Radios
CTRL + ALT + 8 Go Browse
CTRL + SHIFT + S Go Settings
CTRL + ARROW LEFT Prevoius track
CTRL + ARROW RIGHT Next track
SPACE Play/Pause

2024-06-10 10:05 UTC, marcelveldt commented on src/App.vue
> +
this code needs a guard to handle the following cases:
- api connection not (yet) initialized or lost
- no active player 
- no queue actions available

2024-06-10 10:06 UTC, marcelveldt commented on src/layouts/default/HelperShortcuts.vue
Please remove this - keep this PR simple to only provide media controls
In a follow up PR you can do more controls and add config options (to the settings view!)

2024-06-10 10:08 UTC, marcelveldt commented on src/App.vue
> +        e.preventDefault();
Please carefully test all cases where we also listen for keypresses, such as the library listings.
If you are watching a list like Artists or Albums, you should be able to just start typing to interactively search

2024-06-10 10:09 UTC, max246 commented on src/layouts/default/HelperShortcuts.vue
ok cool will do

2024-06-10 10:09 UTC, marcelveldt requested changes
see in-line feedback - keep the PR small and simple and focus only on the media controls. Also, you are only accounting for the happy flow now. If the api connection is not there yet or no player is active this will crash

2024-06-12 16:19 UTC, max246 commented on src/App.vue
> +        e.preventDefault();
I did try and it wasnt affecting it

2024-07-08 23:18 UTC, marcelveldt commented
I've just tested this PR and it was not working, especially not in the subpages. 
So back to the drawing board, we might want to look into mediaSession again

2024-10-14 12:38 UTC, OzGav commented
@max246 Do you want to progress this?

2024-10-14 12:44 UTC, max246 commented
> @max246 Do you want to progress this?

Yeah sorry I got bit busy at work. 
I need to dig up more how media access works since when I tried didn't seem to do anything. 

If you have any tips or you want to collaborate let me know

2024-12-23 09:00 UTC, marcelveldt commented
superseded by #769

2024-12-23 09:00 UTC, closed without merging